extends:
  - "spectral:oas"

rules:

  # ---------------------------------------------------------------------------
  # Schema rules
  # ---------------------------------------------------------------------------
  info-version-semver:
    severity: error
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version.
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+.[0-9]+.[0-9]+)$"

  cicd-demo-tags-need-description:
    description: all tags must have a description
    given: $.tags[*]
    severity: error
    then:
      field: description
      function: truthy

  server-url-must-contain-version:
    description: Global API version must be present in the path
    severity: error
    recommended: true
    message: "Unversioned server URL detected: {{value}}"
    given: "$.servers[*].url"
    then:
      function: pattern
      functionOptions:
        match: "\/v[1-9]+\/"
      
  operation-id-camelcase:
    description: "Operation IDs should follow camelCase naming convention."
    given: "$.paths[*][*].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-zA-Z0-9]*$"
